export const SCENES = {
  dex_arb: {
    name: 'DEX 套利',
    styleHint: '稳健 · 骗局少、收益平',
    rarityWeights: { common: 65, rare: 25, epic: 8, legendary: 2 },
    scamRate: 0.05,
    botPreference: null,
  },
  new_token: {
    name: '新币发射台',
    styleHint: '激进 · 骗局多但稀有牌多，高风险高回报',
    rarityWeights: { common: 50, rare: 35, epic: 10, legendary: 5 },
    scamRate: 0.3,
    botPreference: 'Shadow',
  },
  nft_market: {
    name: 'NFT 市场',
    styleHint: '均衡 · 中等骗局，偏稀有',
    rarityWeights: { common: 50, rare: 35, epic: 13, legendary: 2 },
    scamRate: 0.15,
    botPreference: 'Phantom',
  },
  lending: {
    name: '借贷清算',
    styleHint: '高收益 · 骗局少、稀有牌多',
    rarityWeights: { common: 55, rare: 25, epic: 15, legendary: 5 },
    scamRate: 0.08,
    botPreference: null,
  },
}

export const LAYER_CONFIG = {
  1: {
    scene: 'dex_arb',
    bot: null,
    isTutorial: true,
    isBoss: false,
    tutorialCards: [
      {
        id: 'tutorial_1_scam',
        type: 'arbitrage',
        rarity: 'epic',
        isScam: true,
        expectedProfit: 3.8,
        displayedRisk: 0.08,
        trueRisk: 0.92,
        gasCost: 55,
        timeWindowSec: 28,
        competitionLevel: 2,
        riskReason: '低风险高利润的伪装机会，真实流动性很差',
      },
      {
        id: 'tutorial_1_arbitrage',
        type: 'arbitrage',
        rarity: 'rare',
        expectedProfit: 0.85,
        displayedRisk: 0.18,
        trueRisk: 0.18,
        gasCost: 32,
        timeWindowSec: 35,
        competitionLevel: 1,
        riskReason: '跨池价差稳定，风险和牌面一致',
      },
      {
        id: 'tutorial_1_liquidation',
        type: 'liquidation',
        rarity: 'rare',
        expectedProfit: 0.72,
        displayedRisk: 0.22,
        trueRisk: 0.22,
        gasCost: 38,
        timeWindowSec: 24,
        competitionLevel: 1,
        riskReason: '清算窗口明确，适合低风险练手',
      },
      {
        id: 'tutorial_1_sandwich',
        type: 'sandwich',
        rarity: 'common',
        expectedProfit: 0.62,
        displayedRisk: 0.3,
        trueRisk: 0.3,
        gasCost: 36,
        timeWindowSec: 21,
        competitionLevel: 2,
        riskReason: '夹击要卡交易前后顺序，Gas 太低容易排不上',
      },
      {
        id: 'tutorial_1_front_run',
        type: 'front_run',
        rarity: 'common',
        expectedProfit: 0.58,
        displayedRisk: 0.34,
        trueRisk: 0.34,
        gasCost: 42,
        timeWindowSec: 18,
        competitionLevel: 2,
        riskReason: '抢跑是正面拼出价，预算不足时优势很快消失',
      },
      {
        id: 'tutorial_1_nft',
        type: 'nft_snipe',
        rarity: 'rare',
        expectedProfit: 1.05,
        displayedRisk: 0.46,
        trueRisk: 0.46,
        gasCost: 45,
        timeWindowSec: 14,
        competitionLevel: 2,
        riskReason: 'NFT 抢购回报飘，窗口短，适合先观察风险',
      },
    ],
  },
  2: {
    scene: 'dex_arb',
    bot: null,
    isTutorial: true,
    isBoss: false,
    tutorialCards: [
      {
        id: 'tutorial_2_arbitrage',
        type: 'arbitrage',
        rarity: 'common',
        expectedProfit: 0.7,
        displayedRisk: 0.18,
        trueRisk: 0.18,
        gasCost: 30,
        timeWindowSec: 34,
        competitionLevel: 1,
        riskReason: '套利利润不高但稳定，少量 Gas 就能观察到正 EV',
      },
      {
        id: 'tutorial_2_sandwich',
        type: 'sandwich',
        rarity: 'rare',
        expectedProfit: 1.15,
        displayedRisk: 0.32,
        trueRisk: 0.32,
        gasCost: 48,
        timeWindowSec: 22,
        competitionLevel: 2,
        riskReason: '夹击牌最吃 Gas，溢价能明显抬成功率',
      },
      {
        id: 'tutorial_2_front_run',
        type: 'front_run',
        rarity: 'rare',
        expectedProfit: 1.05,
        displayedRisk: 0.28,
        trueRisk: 0.28,
        gasCost: 44,
        timeWindowSec: 18,
        competitionLevel: 2,
        riskReason: '抢跑是出价博弈，Gas 低容易被盖过',
      },
      {
        id: 'tutorial_2_liquidation',
        type: 'liquidation',
        rarity: 'common',
        expectedProfit: 0.64,
        displayedRisk: 0.24,
        trueRisk: 0.24,
        gasCost: 34,
        timeWindowSec: 28,
        competitionLevel: 1,
        riskReason: '清算看目标是否还有效，堆太多 Gas 未必换来同等收益',
      },
      {
        id: 'tutorial_2_nft',
        type: 'nft_snipe',
        rarity: 'rare',
        expectedProfit: 1.35,
        displayedRisk: 0.42,
        trueRisk: 0.42,
        gasCost: 52,
        timeWindowSec: 14,
        competitionLevel: 2,
        riskReason: 'NFT 抢购回报高但窗口短，Gas 和波动都更刺激',
      },
    ],
  },
  3: {
    scene: 'dex_arb',
    bot: 'Bot-404',
    isTutorial: true,
    isBoss: false,
    tutorialCards: [
      {
        id: 'tutorial_3_nft',
        type: 'nft_snipe',
        rarity: 'rare',
        expectedProfit: 1.35,
        displayedRisk: 0.42,
        trueRisk: 0.42,
        gasCost: 50,
        timeWindowSec: 16,
        competitionLevel: 2,
        riskReason: 'NFT 抢购收益飘，最容易被对手抢',
      },
      {
        id: 'tutorial_3_arbitrage',
        type: 'arbitrage',
        rarity: 'common',
        expectedProfit: 0.45,
        displayedRisk: 0.12,
        trueRisk: 0.12,
        gasCost: 26,
        timeWindowSec: 38,
        competitionLevel: 1,
        riskReason: '低风险套利，EV 稳定为正',
      },
    ],
  },
  4: { scene: 'dex_arb', bot: 'Shadow', isTutorial: false, isBoss: false },
  5: { scenes: ['dex_arb', 'new_token'], bot: 'Shadow', isBoss: false },
  6: { scenes: ['dex_arb', 'new_token'], bot: 'Shadow', isBoss: false },
  7: { scenes: ['dex_arb', 'new_token'], bot: 'Shadow', isBoss: true },
  8: { scene: 'nft_market', bot: 'Phantom', isBoss: false },
  9: { scenes: ['nft_market', 'lending'], bot: 'Phantom', isBoss: false },
  10: { scenes: ['nft_market', 'lending'], bot: 'Phantom', isBoss: false },
  11: { scenes: ['nft_market', 'lending'], bot: 'Phantom', isBoss: false },
  12: { scenes: ['nft_market', 'lending'], bot: 'Phantom', isBoss: true },
  13: { scene: 'lending', bot: 'Phantom+', isBoss: false },
  14: { scenes: ['nft_market', 'lending', 'new_token'], bot: 'Phantom+', isBoss: false },
  15: { scenes: ['nft_market', 'lending', 'new_token'], bot: 'Phantom+', isBoss: false },
  16: { scenes: ['nft_market', 'lending', 'new_token'], bot: 'Phantom+', isBoss: false },
  17: { scenes: ['nft_market', 'lending', 'new_token'], bot: 'Phantom+', isBoss: true },
  18: { scenes: ['dex_arb', 'nft_market', 'lending', 'new_token'], bot: 'Genesis', isBoss: false },
  19: { scenes: ['dex_arb', 'nft_market', 'lending', 'new_token'], bot: 'Genesis', isBoss: false },
  20: { scenes: ['dex_arb', 'nft_market', 'lending', 'new_token'], bot: 'Genesis', isBoss: true },
}
